### PR TITLE
add link to cryptonomica.net 

### PR DESCRIPTION
**Pull request by ageyev**
Cryptonomica OpenPGP online:  https://cryptonomica.net/#!/openPGPOnline

### CODE REVIEW

**Comment by dschuermann** [comment]
The page is only for email encryption. This looks more like a developer tool. Can you add it here: _software/03-developer-tools.md please?

**Comment by ageyev** [comment]
It's for end users, not for developers. 
It provides key generation, key information reading, signing text, signature verification in browser.

**Comment by ageyev** [comment]
Can we make a page for general purpose OpenPGP software? Like GNU Privacy Guard, Kleopatra, GPG Suite etc.

**Comment by dschuermann** [comment]
Yep, Sounds good. Can you make a proposal for such a section in this process?

**Comment by dschuermann** [comment]
Please open a new pull request if you still pursue this.

**Comment by dschuermann** [comment]
Tanks to #33 your Project is now here: https://www.openpgp.org/software/misc/

**Comment by ageyev** [comment]
Thank you!

**Pull request closed without merging**
