### PR TITLE
Update outdated links (FlowCrypt)

### PR DESCRIPTION
**Pull request by vahram-papazyan**

### CODE REVIEW

**Comment by teythoon** [comment]
Would you be so kind to rebase your change and provide it as one single commit?

**Comment by tomholub** [comment]
@martgil could you please make a new PR that has all these changes as a single commit? Thanks!

**Comment by martgil** [comment]
Yes - I have prepared and publish a new PR that satisfy all the requested changes - https://github.com/OpenPGP/openpgp.org/pull/129

**Comment by teythoon** [comment]
Merged in #128.

**Comment by martgil** [comment]
Thanks!

**Pull request closed without merging**
